name: hdparm # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: HD Parm
description:
  Hard Drive Parmaeters

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hdparm:
    command: /sbin/hdparm

parts:
  hdparm:
    plugin: nil
    stage-packages: [hdparm]
